### ISSUE TITLE
NetBSD port

### ISSUE THREAD

**Issue by 0-wiz-0** [johalun/sysctl-rs#70]
I've started a NetBSD port based mostly on the FreeBSD one. My work is [here](https://github.com/0-wiz-0/sysctl-rs).

It currently fails to build:
```
   Compiling sysctl v0.6.0 (sysctl-rs-fork)
error[E0425]: cannot find function `sysctlnametomib` in crate `libc`
  --> src/unix/funcs.rs:26:15
   |
26 |         libc::sysctlnametomib(
   |               ^^^^^^^^^^^^^^^ not found in `libc`

error[E0599]: no method named `is_temperature` found for struct `ctl_info::CtlInfo` in the current scope
   --> src/unix/funcs.rs:199:13
    |
199 |     if info.is_temperature() {
    |             ^^^^^^^^^^^^^^ method not found in `CtlInfo`
    |
   ::: src/ctl_info.rs:8:1
    |
8   | pub struct CtlInfo {
    | ------------------ method `is_temperature` not found for this struct

error[E0425]: cannot find function `temperature` in this scope
   --> src/unix/funcs.rs:200:16
    |
200 |         return temperature(&info, &val);
    |                ^^^^^^^^^^^ not found in this scope

```
The first is a problem in the libc crate which @0323pin is working on fixing.
I'm a bit confused by the other too - how do these work on other non-FreeBSD systems? I don't see `is_temperature()` defined except for FreeBSD, but I must have overlooked something.

**Comment by 0323pin** [comment]
> The first is a problem in the libc crate which @0323pin is working on fixing.

For reference, https://github.com/rust-lang/libc/pull/3927

**Comment by johalun** [comment]
First, I assume that NetBSD doesn't have the temperature type? If that's the case, check src/unix/funcs.rs:200 where it returns the temperature. We might have to make 
```
    // Special treatment for temperature ctls.
    if info.is_temperature() {
        return temperature(&info, &val);
    }

```
only run on FreeBSD. If NetBSD does have it, we need to enable the type for NetBSD, in addition to FreeBSD.

**Comment by 0-wiz-0** [comment]
NetBSD provides temperature information using [envsys](https://man.netbsd.org/envsys.4), not sysctl. Here's [some example rust code](https://github.com/0-wiz-0/rust-envsys).
I was confused because I assumed that the `unix` code was for macOS and Linux too, and then I didn't understand why it worked on those systems.
Yes, we'll need to make this part FreeBSD-only, what's the best way to do that?

**Comment by johalun** [comment]
You could try something like
```
    // Special treatment for temperature ctls.
    #[cfg(target_os = "freebsd")]
    if info.is_temperature() {
        return temperature(&info, &val);
    }
```
If this works, that's good for now. Although, I rather we test for features (like `#[cfg(feature = "temperature")]` or similar), than target_os all over the place but that's out of the scope for this work. Maybe something I'll work on later.

**Comment by 0-wiz-0** [comment]
Thanks. I just pushed a change based on your suggestion, now I'm down to the mib issue.
```
   Compiling sysctl v0.6.0 (/disk/storage-202004/archive/foreign/sysctl-rs-fork)
error[E0425]: cannot find function `sysctlnametomib` in crate `libc`
  --> src/unix/funcs.rs:26:15
   |
26 |         libc::sysctlnametomib(
   |               ^^^^^^^^^^^^^^^ not found in `libc`

warning: unreachable pattern
   --> src/unix/funcs.rs:227:9
    |
227 |         _ => Err(SysctlError::UnknownType),
    |         ^
    |
    = note: `#[warn(unreachable_patterns)]` on by default

For more information about this error, try `rustc --explain E0425`.
warning: `sysctl` (lib) generated 1 warning
error: could not compile `sysctl` (lib) due to 1 previous error; 1 warning emitted
```
so we'll have to wait to get that merged first.

**Comment by johalun** [comment]
In your pull request, please also add NetBSD to Cirrus CI in the file `.cirrus.yml`.

**Comment by 0-wiz-0** [comment]
I don't see how to add NetBSD to the Cirrus image.
On https://cirrus-ci.org/guide/FreeBSD/ I get docs for FreeBSD and next to it for Linux and macOS.
Other project use crosscompilation:
[trippy](https://github.com/fujiapple852/trippy/blob/master/.github/workflows/ci.yml)
[trash-rs](https://github.com/Byron/trash-rs/blob/master/.github/workflows/rust.yml)

**Comment by johalun** [comment]
I found https://github.com/haskell/bytestring/blob/master/.cirrus.yml which uses their custom VM instances. Maybe that'll work?

https://cirrus-ci.org/guide/custom-vms/

Apparently their FreeBSD instance is already of this type
> Already things like [Docker Builder](https://cirrus-ci.org/guide/docker-builder-vm/) and [freebsd_instance](https://cirrus-ci.org/guide/FreeBSD/) are basically a syntactic sugar for launching Compute Engine instances from a particular limited set of images.

**Comment by 0-wiz-0** [comment]
Using @0323pin 's libc and after adapting the example code, I get, for `cargo test`:
```
running 11 tests
test ctl_value::tests_unix::ctl_struct_type ... ok
test sys::ctl::tests::ctl_new ... ok
test ctl_flags::tests::ctl_flags ... FAILED
test sys::ctl_iter::tests::ctl_iter_iterate_all ... FAILED
test sys::funcs::tests::ctl_name ... FAILED
test sys::funcs::tests::name2oid_invalid_name ... ok
test ctl_value::tests_unix::ctl_value_string ... FAILED
test sys::ctl::tests::ctl_description ... FAILED
test ctl_value::tests_unix::ctl_value_int ... FAILED
test ctl_value::tests_unix::ctl_value_oid_int ... FAILED
test sys::funcs::tests::ctl_type ... FAILED

failures:

---- ctl_flags::tests::ctl_flags stdout ----
thread 'ctl_flags::tests::ctl_flags' panicked at src/ctl_flags.rs:84:50:
called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- sys::ctl_iter::tests::ctl_iter_iterate_all stdout ----
thread 'sys::ctl_iter::tests::ctl_iter_iterate_all' panicked at src/unix/ctl_iter.rs:86:9:
assertion `left != right` failed
  left: 0
 right: 0

---- sys::funcs::tests::ctl_name stdout ----
thread 'sys::funcs::tests::ctl_name' panicked at src/unix/funcs.rs:869:42:
Could not get name of kern.osrevision sysctl.: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })

---- ctl_value::tests_unix::ctl_value_string stdout ----
thread 'ctl_value::tests_unix::ctl_value_string' panicked at src/ctl_value.rs:118:9:
assertion `left == right` failed
  left: "..."
 right: "NetBSD 10.99.12 (GENERIC) #1: Tue Sep 10 14:25:35 CEST 2024\n\twiz@exadelic.gatalith.at:/disk/storage-202004/archive/foreign/src/sys/arch/amd64/compile/obj/GENERIC"

---- sys::ctl::tests::ctl_description stdout ----
thread 'sys::ctl::tests::ctl_description' panicked at src/unix/ctl.rs:299:9:
assertion failed: descp.is_ok()

---- ctl_value::tests_unix::ctl_value_int stdout ----
thread 'ctl_value::tests_unix::ctl_value_int' panicked at src/ctl_value.rs:145:9:
assertion `left == right` failed
  left: 0
 right: 1099001200

---- ctl_value::tests_unix::ctl_value_oid_int stdout ----
thread 'ctl_value::tests_unix::ctl_value_oid_int' panicked at src/ctl_value.rs:162:9:
assertion `left == right` failed
  left: 0
 right: 1099001200

---- sys::funcs::tests::ctl_type stdout ----
thread 'sys::funcs::tests::ctl_type' panicked at src/unix/funcs.rs:883:39:
called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })


failures:
    ctl_flags::tests::ctl_flags
    ctl_value::tests_unix::ctl_value_int
    ctl_value::tests_unix::ctl_value_oid_int
    ctl_value::tests_unix::ctl_value_string
    sys::ctl::tests::ctl_description
    sys::ctl_iter::tests::ctl_iter_iterate_all
    sys::funcs::tests::ctl_name
    sys::funcs::tests::ctl_type

test result: FAILED. 3 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--lib`
```
